### ISSUE TITLE
Supervisor service not starting on boot...

### ISSUE THREAD

**Issue by topranks** [oldsj/netbox-playbook#1]
This is not an issue with this playbook as such, however it seems the supervisor package for 16.04 currently does not correctly start the service on boot (some issue with move to systemd no doubt).

See answer 2 on the following page for more info:

https://unix.stackexchange.com/questions/281774/ubuntu-server-16-04-cannot-get-supervisor-to-start-automatically

The solution for now is to issue "systemctl enable supervisor.service" manually to get systemd to start the service on boot.  I am not sure if you'd rather wait for the issue to be resolved with supervisor on 16.04 or possibly include this step in your playbook as a workaround.

Thanks again,

Cathal.

**Comment by oldsj** [comment]
Thanks for reporting this, I added a task to explicitly enable the supervisor service and after a reboot it looks good.
